[#60] 나의 대시보드 페이지 구현
part3-4/Taskify pull request #109
Opened 2023-12-30 08:39 UTC by zermzerm

## ✅ 작업 내용

- [x] 새로운 대시보드 버튼들 + 페이지네이션
- [x] 초대받은 대시보드 컴포넌트 대입

## 📍 리뷰 포인트

대시보드 추가하기
페이지네이션
무한스크롤
검색
수락 거절

## 👀 기타 사항

- mydashboard 페이지로 가면 보입니다!

![image](https://github.com/part3-4/Taskify/assets/91651812/2ed5bf5b-43ba-4fd3-86c0-b211102aee85)
![image](https://github.com/part3-4/Taskify/assets/91651812/28b54003-21a0-43e5-b9b9-ea7daedd8433)

2023-12-30 11:55 UTC, qooktree1 approved these changes
고생하셨습니다!!

2023-12-30 11:55 UTC, qooktree1 commented on components/MyDashboard/MyDashBoardButtonBox.tsx
> +  // });
필요없는 주석은 삭제해도 될것 같아요!

2023-12-30 11:55 UTC, qooktree1 commented on components/common/Button/TwinButton.tsx
>    isDisabled?: boolean;
옵셔널 체이닝을 사용하여 다른 코드에서는 문제 없이 동작하게 하셨군요 굳 👍👍

2023-12-30 11:55 UTC, qooktree1 commented on pages/mydashboard/index.tsx
> +  const dashboardId = 203; // 대시보드 아이디 여기 수정하면 됩니다
로그인코드와 대시보드 아이디는 빼셔도 될 것 같습니다!

2023-12-30 12:13 UTC, zermzerm commented on components/common/Button/TwinButton.tsx
>    isDisabled?: boolean;
조습니다 종민님 덕분입니다

2023-12-30 12:13 UTC, zermzerm commented on pages/mydashboard/index.tsx
> +  const dashboardId = 203; // 대시보드 아이디 여기 수정하면 됩니다
오 감사합니다!

2024-01-01 03:43 UTC, oauch approved these changes
위워크 대장님(?) 수고하셨습니다👍🏻

2024-01-01 03:43 UTC, oauch commented on components/Chip/ColorChip.tsx
> +    setSelectedColor((prevSelectedColor) => (prevSelectedColor === index ? -1 : index));
명시적 표현 조습니다 🦈

2024-01-01 03:43 UTC, oauch commented on components/Modal/Modal.tsx
> +  height: 100%;
모달 배경 부분 해결했던 부분이군요 👍🏻

2024-01-01 03:43 UTC, oauch commented on components/MyDashboard/MyDashBoardButtonBox.tsx
> +  const limit = 5;
만약 고정된 값이라면 이 값은 컴포넌트 밖에다 선언하는게 어떨까요?
렌더링 될 때마다 계속 선언 될 꺼 같습니다 👻

2024-01-01 03:43 UTC, oauch commented on components/common/Button/DashBoardButton.tsx
>   * @param king 대시보드 생성자 여부 boolean
king ㅋㅋㅋㅋ

2024-01-01 03:43 UTC, oauch commented on hooks/usePagination.ts
> +  console.log('REF', resetToFirst);
콘솔은 리팩토링 하면서 지우실꺼죠? 👀

2024-01-01 04:07 UTC, summerkimm approved these changes
드디어 마무리 하셨군여 👏 고생많으셨습니다!

2024-01-01 04:07 UTC, summerkimm commented on components/MyDashboard/MyDashBoardButtonBox.tsx
> +            setIsOpen(false);
취소 버튼이 동작하지 않네요🥲 확인이 필요할 것 같습니당!

2024-01-01 04:46 UTC, zermzerm reviewed
감삼다

2024-01-01 04:46 UTC, zermzerm commented on components/MyDashboard/MyDashBoardButtonBox.tsx
> +  const limit = 5;
오 조습니다

2024-01-01 04:46 UTC, zermzerm commented on components/MyDashboard/MyDashBoardButtonBox.tsx
> +            setIsOpen(false);
감사합니다 고쳤습니다 조습니다 👍

2024-01-01 04:46 UTC, zermzerm commented on hooks/usePagination.ts
> +  console.log('REF', resetToFirst);
종민님의 유산이 남아 있었네요. 지웠습니다!

2024-01-01 14:17 UTC, arky02 commented on components/Modal/ModalContent/CreateDashboard.tsx
> +    색상: '#7AC555',
이거 colorchip을 미리 설정된 저 색상으로(아마 초록색인거같은데) 처음에 디폴트로 체크되게 고쳐야할 것 같아요!! 그리고 colorchip 토글 안되고 무조건 하나가 선택되게 고쳐야할 것 같아요!!!

2024-01-01 14:23 UTC, arky02 requested changes
경서님 수고하셨어요!!! 그 태블릿 사이즈일때에는 가로 공백? 이 생기고 pc 사이즈일 때는 가로 세로 화면 공백 여분이 생기더라고요!!! width랑 height만 조절되면 완벽할 것 같습니다!!!! 일단 request changes 드릴게요 수정하시고 머지하심 될거같아요 굿입니다요~

2024-01-01 14:23 UTC, arky02 commented on components/MyDashboard/MyDashBoardButtonBox.tsx
> +  });
경서님 이거 제가 constant/InitialModalValues에 상수로 설정해뒀어요! 그래서 import 해오셔서 useState(INIT_CREATE_DASHBOARD)로 사용하시면 됩니다

2024-01-01 14:23 UTC, arky02 commented on components/MyDashboard/MyDashBoardButtonBox.tsx
> +const limit = 5;
상수는 알아보기 쉽게 대문자로 쓰면 좋을 것 같아요!

2024-01-01 14:23 UTC, arky02 commented on components/MyDashboard/MyDashBoardButtonBox.tsx
> +            setIsOpen(false);
심쿵했습니다 해결되서 다행입니다요

2024-01-01 14:23 UTC, arky02 commented on components/common/Button/DashBoardButton.tsx
>   * @param king 대시보드 생성자 여부 boolean
king받네요

2024-01-01 14:27 UTC, arky02 commented
아 경서님 그리고 대시보드 이름에 아무것도 입력 안했을 때 막아야할 것 같아요!! 흠.. 버튼을 disabled 시키던지 api 요청을 보낼 때 조건 확인해서 이름 안적었으면 무시하던지 방법을 생각해봐야 할 것 같네요!!!!

2024-01-02 04:32 UTC, zermzerm commented on components/Modal/ModalContent/CreateDashboard.tsx
> +    색상: '#7AC555',
오 고치겠습니다!

2024-01-02 05:14 UTC, merged