[#17] Feat/landing page
part3-4/Taskify pull request #45
Opened 2023-12-21 11:41 UTC by summerkimm

## ✅ 작업 내용

- [ ] 반응형에 따른 index Page 구현

## 📍 리뷰 포인트
- 아래 동영상 확인해 주세요 
- 아직 수정 못 한 부분 있어ㅓ요... (pointSection)

## 👀 기타 사항
- 늦어서 죄송합니다 🙏
- 피드백 많이 많이 주세요 

https://github.com/part3-4/Taskify/assets/111335529/d03b9854-77cc-456c-87b0-dc2fa4c4eed0

https://github.com/part3-4/Taskify/assets/111335529/943d5ffe-9d00-4a84-9104-c3cd2b0b4172

https://github.com/part3-4/Taskify/assets/111335529/e85dcda4-86ae-4b4a-9711-526051a81b96

2023-12-21 14:21 UTC, summerkimm commented on components/Landing/Card.tsx
> +interface CardContainerProps {
페이지에 코드 길이가 길어지는 것 같아서 각 섹션마다 나눠서 컴포넌트로 분리했습니다.

2023-12-21 14:21 UTC, summerkimm commented on components/Landing/Card.tsx
> +  type: 'first' | 'second' | 'third';
카드들이 이미지 크기를 제외하고 스타일이 동일하기 때문에, 타입을 받아서 값에 따라 이미지 크기가 달라질 수 있도록 했습니다.

2023-12-21 14:21 UTC, summerkimm commented on components/Landing/Card.tsx
> +        <CardContainer
같은 디자인은 컴포넌트로 분리했습니다.

2023-12-21 14:21 UTC, summerkimm commented on components/Landing/Card.tsx
> +      default:
셀프 궁금궁금: 여기 디폴트값은 보통 어떤 것을 주죠? 제 마음대로인가요? 👀 이렇게 순서로 고르는 경우라면 다들 어떻게 하시나요!

2023-12-21 14:21 UTC, summerkimm commented on components/Landing/Hero.tsx
> +      <StyledHeroDescription>서비스의 메인 설명 들어갑니다</StyledHeroDescription>
추후에 이 부분 저희끼리 수정해서 채워야합니다!

2023-12-21 14:21 UTC, summerkimm commented on components/Landing/Point.tsx
> +      <StyledPointSectionWrapper>
여기가 문제의 그리드 부분입니다... 제 머리로는 이미 한계지만 다시 수정해 볼게요.. 피드백 적극 환영

2023-12-21 14:21 UTC, summerkimm commented on components/common/Button/AddButton.tsx
버튼 컴포넌트들은 경서님이 수정하신 부분이고, 제가 pull 받아오는 과정에서 잘못 커밋한 것 같네요 넘어가셔도 됩니다!

2023-12-22 01:30 UTC, arky02 reviewed
수고 많으셨어요!!!! 고생하셨네요ㅜㅜ

2023-12-22 01:30 UTC, arky02 commented on components/Landing/Card.tsx
> +        />
이 부분 텍스트를 constant/ 파일에 위치하게 만들어도 좋을 것 같아요!!

2023-12-22 01:30 UTC, arky02 commented on components/Landing/Card.tsx
> +    'liga' off;
혹시 이 속성은 뭔가요?! 처음보네요!

2023-12-22 01:30 UTC, arky02 commented on components/Landing/Card.tsx
> +      default:
음 무조건 저 3가지경우만 존재한다면 default 값은 안쓰셔두돼요!!! 저 3가지 조건에 다 걸리지 않을 때만 실행되는거라 저 경우들만 존재한다면 reach하지 못할거에요!

2023-12-22 01:30 UTC, arky02 commented on components/Landing/Card.tsx
> +  background-color: #1501cb9c;
혹시 이부분 그 저희가 같이 정했던 연보라색일까요? COLORS파일에 추가해도 좋을 듯 싶네염

2023-12-22 01:30 UTC, arky02 commented on components/Landing/Footer.tsx
> +        </Link>
음 여기 alt도 저같은 경우에는 여러개 쓰이면 const파일에 정리해서 놓긴 하는데 어떠실까욤?? 근데 좀 귀찮을 수도 있어서... 소은님맘대루,,,ㅋㅋㅋ

2023-12-22 01:30 UTC, arky02 commented on components/Landing/Hero.tsx
> +  font-family: Montserrat;
새로운 폰트가 쓰였군요!!

2023-12-22 01:30 UTC, arky02 commented on components/Landing/Point.tsx
> +      'text2 .';
뭔가 고치려면 이 template areas를 포기해야하지않나 싶네요...

2023-12-22 02:27 UTC, oauch requested changes
아직 grid부분 수정 안된 것 같으니까
그 부분 수정 완료되면 어푸하겠습니다 🏊🏻‍♂️

2023-12-22 02:27 UTC, oauch commented on components/Landing/Card.tsx
> +      default:
저는 개인적으로 default 값이 무조건 있어야 된다고 생각하네요
만~~~약 case문에 해당 하지 않는 값이 들어가게 되면 width와 heigth 값이 아무것도 들어가지 않게 될 것 같아서요!

2023-12-22 02:27 UTC, oauch commented on components/Landing/Footer.tsx
> +  background-color: #000;
저희 COLORS로 상수화 시켰으니까 그거 이용하는 것도 좋을 것 같습니다!

2023-12-22 02:27 UTC, oauch commented on components/Landing/Nav.tsx
> +`
밑에 코드들 보니까 onTablet, onPc 순으로 미디어쿼리 사용하신 것 같은데
여기도 순서 맞추면 좋을 것 같습니다!

2023-12-22 04:40 UTC, qooktree1 commented on components/Landing/Card.tsx
> +        />
흠 constant/Landing.ts 안에 상수값들을 저장하는 형태로 말씀이신건가요?

2023-12-22 04:40 UTC, qooktree1 commented on components/Landing/Card.tsx
> +const CardContainer = ({ cardImg, imgAlt, text1, text2, type }: CardContainerProps) => {
컴포넌트 같은 경우는 function으로 수정해도 좋을 것 같아요!

NIT
또, 개인적으로는 CardSection과 Cardcontainer 의 경우 위쪽에 배치하고 나머지 Styled components 같은 경우는 밑에 코드 배치를 하는게 좋아보이네요!

2023-12-22 15:19 UTC, summerkimm commented
기연님 말씀해주신 상수는 나중에 리팩토링 할 시간에 해보겠습니다! 
grid 코드들 다시 보니까 제가 삽질? 했네욤.. 정신차리겠슴다

2023-12-23 06:17 UTC, merged