Login, SignUp 페이지 #74
part3-4/Taskify pull request #81
Opened 2023-12-26 18:07 UTC by arky02

## ✅ 작업 내용

- [x] 로그인 페이지 구현
- [x] 회원가입 페이지 구현
- [x] 로그인, 회원가입 처리 api 구현 
- [x] react-hook-form 적용 
- [x] 라우팅 처리
- [x] formInput 비제어 컴포넌트로 수정 
- [x] 구현하면서 필요한 부분의 기타 컴포넌트들 자잘한 수정

## 📍 리뷰 포인트

- 에러 메세지 처리 어떤지 봐주세요!! 고쳐야 할 점이나 추가해야 할 점! 최대한 안정화하긴했는데 놓친 부분 있을 수 있어서..ㅠ
-

## 👀 기타 사항

-
-

## 로그인 페이지 구현 동영상 
- 서버 에러는 ""존재하지 않는 유저입니다." 에러이고, 버튼 위에 떠요! 나머지는 react-hook-form에서 에러 처리하는 noValue, validation 에러입니다!
https://github.com/part3-4/Taskify/assets/46954114/9232e44c-e96a-4052-a82e-429926827e28

## 회원가입 페이지 구현 동영상
- 서버 에러는 "이메일 형식으로 작성해주세요.",  "이미 사용중인 이메일입니다." 에러입니다! 나머지는 로그인 페이지 에러처리랑 똑같고 추가로 pwdcheck랑 password일치 여부까지 react-hook-form 자체 검증 에러입니다!
https://github.com/part3-4/Taskify/assets/46954114/5de5fe41-4875-44ab-a91a-d4a68773188a

우선은 onBlur일때 에러 검증하게 해뒀습니다.
테스트 코드는 없습니다....
git checkout feat/LoginNSignUp_#74 
하셔서 signup/index, login/index 페이지 봐주세요!!
라우팅 부분까지 구현 했습니다!!

2023-12-26 18:14 UTC, arky02 commented on components/Input/FormInput.tsx
> +  register?: UseFormRegisterReturn;
react-hook-form 쓰면서 어떤 것을 입력받을 것인지 확인하는 register prop을 input에 넘겨줘서 login, signUp 페이지를 좀더 예쁘게(?) 짜려고 했습니다 ㅋㅋㅋ

2023-12-26 18:30 UTC, arky02 reviewed
갑자기 팀미팅 참여 못하게 되어 죄송해요.....자기 전에 (졸려서 쓰러질 것 같지만 (내일 7시에 일어나야 하지만)(3시간 반밖에 못자지만) ㅜㅜㅜ) 최대한 열심히 PR남기고 잘게요 흑흑 시간되면 들어가겠습니다!!!(안될 가능성 80%) 저도 내일 놀러가는지 오늘 알았습니다..모레인줄 알았어욬ㅋㅋㅋ 무릎꿇겠습니다.

2023-12-26 18:30 UTC, arky02 commented on components/Input/FormInput.tsx
> +function FormInput({ label = '', placeholder, errorMessage = '', register }: Props) {
react-hook-form 쓰면 input이 아에 비제어 컴포넌트여도 되서 이거 formInput은 로그인/ 회원가입에만 쓰여서 비제어 컴포넌트로 바꿨습니다! react-hook-form 쓰는 경우 제외하고는 BasicInput 제어 컴포넌트 써주세요!

2023-12-26 18:30 UTC, arky02 commented on components/Input/FormInput.tsx
> +function FormInput({ label = '', placeholder, errorMessage = '', register }: Props) {
이 인풋만 비제어고 나머지는 다 제어컴포넌트입니다!!!

2023-12-26 18:30 UTC, arky02 commented on components/Input/FormInput.tsx
>          </StyledEyeButton>
생각해보니까 이 로직이 반대로 되어있더라구요 글구 초기 visiblity를 false로 줬습니다!

2023-12-26 18:30 UTC, arky02 commented on components/Input/ModalInputContainer/BasicInput.tsx
> +import { NO_VALUE_ERROR } from '@/constants/SignValidate';
이건 그냥 여기 constant 파일에 몇개 더 추가해서 Input보단 Sign하는 로직에 필요한 constant라는거를 표시하기에 이 이름이 날 것 같아서 바꾼거라 무시해도됩니다!

2023-12-26 18:30 UTC, arky02 commented on components/Input/ModalInputContainer/BasicInput.tsx
> +import { NO_VALUE_ERROR } from '@/constants/SignValidate';
제가 하나하나 파일 눌러서 체크해서 파일 이름 다 바꿔뒀어요...... 😅

2023-12-26 18:30 UTC, arky02 commented on components/Landing/Hero.tsx
> +      <LoginButton usingType="landing" active={true} onClick={handleClick} text="로그인하기" />
이것도 제가 react-hook-form 쓸 때 버튼에 type=submit을 줘야 해서 원래 type으로 쓰던 prop이름을 usingType으로 변경하고 사용되던곳에 다 적용했습니다!

2023-12-26 18:30 UTC, arky02 commented on components/common/Button/LoginButton.tsx
> +  usingType: 'login' | 'landing';
바꾼게이겁니다 두개 이름이 겹쳐서..ㅠ

2023-12-26 18:30 UTC, arky02 commented on components/common/Button/LoginButton.tsx
> +const StyledButton = styled.button<{ $active: boolean; $type: string; $margin: string }>`
마진 조절이 필요한데 styled 씌울려면 또 className이랑 children 프롭으로 줘야하는데 이건 그냥 마진만 설정하면 되었어서 마진만 넘겨줬어요!

2023-12-26 18:30 UTC, arky02 commented on constants/ModalInput.ts
> +}));
기존에 input, modalinput이랑 같이 쓰이던 Input 파일을 분리했습니다!! input constant가 sign validate 하는 곳에만 쓰여서 기존 Input에 쓰이던 constant를 validation 상수랑 같이 합쳐서 signValidate 파일 새로 만들었어요!

2023-12-26 18:30 UTC, arky02 commented on constants/SignValidate.ts
> +export const PWD_VALIDATE_PATTERN = /[a-zA-Z]/g && /\d/g;
함수에서 상수로 변경했습니다 react-hook-form validation 방식 떄문에!

2023-12-26 18:30 UTC, arky02 commented on constants/SignValidate.ts
>  };
에러 처리 메세지랑 form input placeholder는 다 여기 써있는 거만 쓰입니다!

2023-12-26 18:30 UTC, arky02 commented on pages/login/index.tsx
> +
onBlur될때 validate 검사 하게 해뒀고, 에러 난 곳에 focus 가게 해뒀습니다!

2023-12-26 18:30 UTC, arky02 commented on pages/login/index.tsx
> +    }
서버 에러를 intercepter가 throw Error 해서 서버 에러가 뜨면 catch로 에러 잡아서 옵셔널로 있으면 에러 메세지 띄우게 해뒀습니다 (일단 에러 타입 any로 해뒀어요)

2023-12-26 18:30 UTC, arky02 commented on pages/login/index.tsx
> +
input 입력되는거 watch 해서 다 입력이 되면 버튼 활성화되게 했습니다 회원가입 페이지도 똑같음!

2023-12-26 18:30 UTC, arky02 commented on pages/login/index.tsx
> +import * as C from '@/constants/SignValidate';
이거 너무 Import 되는게 많아서 Constant라는 의미로 C로 import all 했습니다

2023-12-26 18:30 UTC, arky02 commented on pages/signup/index.tsx
> +import * as C from '@/constants/SignValidate';
마찬가지@!

2023-12-26 18:30 UTC, arky02 commented on pages/signup/index.tsx
> +import * as L from '../login';
로그인 페이지랑 styled-component 겹치는게 많아서 로그인 페이지를 기준으로 겹치는 컴포넌트 export&import 해와서 썼습니다. LoginPage에서 가져왔다는 의미로 L로 import all 해왔습니답

2023-12-26 18:30 UTC, arky02 commented on types/button.ts
> +  onClick?: MouseEventHandler<HTMLButtonElement>;
이거 react-hook-form 쓸 때 알아서 submit 감지해줘서 onClick이 안쓰여서 옵셔널로 바꿨어요@!

2023-12-26 18:30 UTC, arky02 commented on pages/signup/index.tsx
> +
일단 로직은 login이랑 비슷해서(사실 졸려서) 자세한 설명은 생략할게요! 궁금한거나 이해 안가는거 혹은 비난 받을거(ㅜ.ㅜ) 있으면 가차없이 써주세요 전 이만 졸려서 자러...

2023-12-27 00:50 UTC, summerkimm approved these changes
기연님 늦게까지 하느라 고생많으셨어요 👍

2023-12-27 00:50 UTC, summerkimm commented on pages/login/index.tsx
> +          회원이 아니신가요? <StyledLink href="/signup">회원가입하기</StyledLink>
"회원가입하기" 글자랑 선 사이에 간격이 생기면 좋을 것 같아요!

2023-12-27 00:54 UTC, arky02 commented on pages/login/index.tsx
> +          회원이 아니신가요? <StyledLink href="/signup">회원가입하기</StyledLink>
오! 감사합니다 이따 저녁에 수정할게요!

2023-12-27 10:14 UTC, oauch requested changes
수고하셨습니다 많은 부분이 변경 되었네요 👍🏻
아직 수정할 부분이 있는 것 같아서(?) Request Changes 합니다 👀

2023-12-27 10:14 UTC, oauch commented on pages/login/index.tsx
> +
useEffect 사용해야 가능한가요?
```
const handleCheck = () => {
    const password = getValues('password');
    const newPassword = getValues('newPassword');
    const newPasswordCheck = getValues('newPasswordCheck');
    if (password && newPassword && newPasswordCheck) setActivate(false);
  };
```

제가 했던 코드인데 저는 해당 input들 전부 입력되면 `setActivate(false)`로 입력하도록 하니까 useEffect 사용 안해도 가능하더라고요!

이 부분은 나중에 파라미터로 값 받아와서 비교하는 방식으로 함수 만들어 봐도 좋을꺼 같습니다
비슷한 동작을 하는 것 같아서요 👻

2023-12-27 10:14 UTC, oauch commented on types/button.ts
> +  onClick?: MouseEventHandler<HTMLButtonElement>;
저도 이 부분 수정했던거 같은데 👀

2023-12-27 10:14 UTC, oauch commented on pages/signup/index.tsx
> +  passwordRef.current = watch('password');
혹시 이거 password 부분 값 알고 싶어서 이렇게 사용하신거면
제가 위에 댓글에도 남겨 드렸는데, react-hook-form에 있는 `getValues` 사용하는 것도 좋을 것 같습니다😶

2023-12-27 10:14 UTC, oauch commented on components/common/Button/LoginButton.tsx
> +        type={type}
이름을 다르게 해주는 것이 좋을 것 같습니다
같은 이름이면 헷갈릴 수 있을 것 같아요 🥲

2023-12-27 15:42 UTC, arky02 commented on components/common/Button/LoginButton.tsx
> +        type={type}
아 그러면 저거 $type를 $usingType 으로 바꿀까요?

2023-12-27 15:43 UTC, arky02 commented on pages/signup/index.tsx
> +  passwordRef.current = watch('password');
오....! 좋은 방법이네요 적용할게요!

2023-12-28 01:44 UTC, arky02 commented on components/common/Button/LoginButton.tsx
> +        type={type}
바꿨습니다 해결 완료!

2023-12-29 01:28 UTC, oauch approved these changes
LGTM!

2023-12-29 01:28 UTC, merged